### ISSUE TITLE
When I use the command site:install and add the option --skip-exists-check

### ISSUE THREAD

**Issue by TheJenne18** [joomlatools/joomlatools-console#101]
When I execute this command: `vendor/bin/joomla site:install --skip-exists-check --www=website --mysql-login=XXX:XXX --mysql-host=XXX --mysql-database=XXX www.testpakket.be`

I receive the following error: `database with name XXX already exists.` -> `Install.php:152`

**Comment by stevenrombauts** [comment]
Hi @TheJenne18, thanks for reporting this issue. This has been resolved in the latest 1.5.3 release!
