### ISSUE TITLE
PHP Notice:  Undefined property: stdClass::$name

### ISSUE THREAD

**Issue by nobicycle** [joomlatools/joomlatools-console#111]
# Describe your environment
$ uname -a
Linux tower 5.2.8-1-MANJARO #1 SMP PREEMPT Fri Aug 9 19:34:20 UTC 2019 x86_64 GNU/Linux
$ joomla --version
Joomla Console tools 1.5.3

Are you working on the Joomlatools Vagrant box: no

## Describe the problem:
PHP Notice:  Undefined property: stdClass::$name in /srv/http/.composer/vendor/joomlatools/console/src/Joomlatools/Console/Joomla/Ut

#### Steps to reproduce:
[me@tower http]$ sudo -u http joomla  site:list --www /srv/http
PHP Notice:  Undefined property: stdClass::$name in /srv/http/.composer/vendor/joomlatools/console/src/Joomlatools/Console/Joomla/Util.php on line 140
2. salon (joomla-cms 3.9.11)

#### Observed Results:

A PHP Notice.

**Comment by stevenrombauts** [comment]
@nobicycle Thanks for the report, this notice has been fixed and will be gone in the next release!
