### ISSUE TITLE
Make joomlatools-console home configurable

### ISSUE THREAD

**Issue by Hermsi1337** [joomlatools/joomlatools-console#120]
### Describe your environment

  * OS: Linux
  * Joomla version: 3
  * Joomlatools Console version: v1.5.6
  * Are you working on the Joomlatools Vagrant box: no

### Describe the problem:

The `joomlatools`-console determines it's home directory by using the pre-defined `$HOME` variable, which is okay in most cases.  
In our case, we're running the console in a managed-hosting environment, where the `$HOME`-directory is NOT writable, which results in an error when running the `joomla` command.

It would be great, if there is a way to configure the home directory for `joomlatools`-console by using a variable equivalent to [`COMPOSER_HOME`](https://getcomposer.org/doc/03-cli.md#composer-home). Maybe `JOOMLATOOLS_CONSOLE_HOME`?

I'm thinking about adjusting the [`getConsoleHome()`](https://github.com/joomlatools/joomlatools-console/blob/4a08c2c1a9dffd9afe99ead03318db7019f799e5/src/Joomlatools/Console/Application.php#L90
)-function like that:

```php
    /**
     * Get the home directory path
     *
     * @return string Path to the Joomlatools Console home directory
     */
    public function getConsoleHome()
    {
        $home = getenv('HOME');
        if (getenv("JOOMLATOOLS_CONSOLE_HOME") !== "") {
            $home = getenv("JOOMLATOOLS_CONSOLE_HOME");
        }
        return rtrim($home, '/') . '/.joomlatools/console';
    }
```

Doing it that way we should also ensure backwards-comaptibility.  
Since I'm not very familiar with best-practice-php-programming I'm open for suggestions.

#### Steps to reproduce:

  1. Install `joomlatools`-console to a managed-hosting environment, e.g. [mittwald](https://www.mittwald.de)
  2. Run any command

#### Observed Results:

  * Error: /path/to/home is not writable

#### Expected Results:

  * That it's possible to override the default home for `joomlatools`-console.

**Comment by stevenrombauts** [comment]
@Hermsi1337 This is a great suggestion and would make a lot of sense to be able to overwrite the default HOME directory. The fix you suggest should work great! Feel free to send that in as a PR.
