### ISSUE TITLE
box php:use 7.4.4 

### ISSUE THREAD

**Issue by tonypartridge** [joomlatools/joomlatools-console#122]
When I try and get box to use 7.4.4 it fails with an old bison version. I've upgrade it to 3.3.2 and confirming that via  bison -V. But it appears box php:use is somehow using 2.3 still. Advise on resolving this?

**Comment by johanjanssens** [comment]
Thanks @tonypartridge could you please use our community channels to report issues, the Github trackers are used for development and submission of PR's. We have a forum and a chat:

- https://groups.google.com/forum/?pli=1#!forum/joomlatools-dev
- http://gitter.im/joomlatools/dev

Thanks!
