### ISSUE TITLE
Make the console ubiqutious

### ISSUE THREAD

**Issue by yiendos** [joomlatools/joomlatools-console#127]
At present the JT console box is heavily dependent on the joomlatools-vagrant. Increasingly we are seeing the need for these commands on: 

* gitpod 
* github actions 
* docker containers 

My idea is that a lot of the defaults (www | mysql_host | user | password | php) could be provided by system environment variables. 

This way we can still easily use `joomla site:create testing` for a range of different environments

**Comment by stevenrombauts** [comment]
@yiendos FYI, this is related to these tickets:

* https://github.com/joomlatools/joomlatools-console/issues/12
* https://github.com/joomlatools/joomlatools-console/issues/16

The easiest solution would be to create a separate `Configuration` option that will have all the default (just like Joomla's configuration.php file) but can load settings from an ini or yaml file (which we could look for at a default location, ie `$HOME/.console/config.yaml`?

**Comment by yiendos** [comment]
@stevenrombauts config files would be much better than ENVs indeed. Top thinking ah'kid :)

**Comment by amazeika** [comment]
@yiendos Not sure the work I've done cover all your needs but please check it out => #132
