### ISSUE TITLE
Fix plugin installations

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-console#48]
Since Composer 1.0 release we are unable to install plugins. The `composer show --all` command does not work anymore: https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Command/Plugin/Install.php#L66 and should be replaced by whatever is now required to fetch package info.

**Comment by stevenrombauts** [comment]
This was actually already fixed in 4546cab6d but depending on Composer version this seems to fail still.

Works on 1.2-dev
Fails on 1.1.2

**Comment by rodolfovillaruz** [comment]
On installing `./composer.phar show --all <package>` where composer is version `1.1.2`, is seems to work on showing a certain package information.

Do you have list of plugin that should be tried to show it fails.

**Comment by stevenrombauts** [comment]
@rodolfovillaruz There are only three plugins publicly available right now ([full list](https://github.com/joomlatools?utf8=%E2%9C%93&query=joomlatools-console-)):

* joomlatools/console-capistrano
* joomlatools/console-joomlatools
* joomlatools/console-backup

If they all work then I guess we can mark this ticket as invalid?

**Comment by rodolfovillaruz** [comment]
Ok, closing the issue.

**Comment by johanjanssens** [comment]
Added invalid label.
