### ISSUE TITLE
Use proxy environment variables (if set) for downloading

### ISSUE THREAD

**Issue by scottparsloe** [joomlatools/joomlatools-console#49]
Allow Joomla package and web installer to be downloaded using proxy environment variables, if set. cURL, if installed/enabled, might prove useful for this.

**Comment by stevenrombauts** [comment]
Hi @scottparsloe! The issue tracker is only for planned features, not for questions or suggestions. For questions or discussion of our open tools you can use our [Gitter chat](https://gitter.im/joomlatools/dev) or [forums](https://groups.google.com/forum/#!forum/joomlatools-dev).

We don't have a use-case for proxy connections so we will not put this in our feature tracker now. We are always happy to accept a pull request!

For more info on how to contribute please read our contributions guidelines: https://www.joomlatools.com/developer/contribute/#using-the-issue-tracker
