### ISSUE TITLE
Requirement: git

### ISSUE THREAD

**Issue by markboos** [joomlatools/joomlatools-console#51]
It's logical but without the git package, downloading the Joomla! versions won't work. It isn't mentioned in the installation nor in the requirements:

Requirements
    Composer
    Joomla version 2.5 and up.

**Comment by stevenrombauts** [comment]
I've added it to the README's requirements section. We assume git is installed, just as we would assume you'd have a working PHP installation and a webserver to run Joomla sites so I don't think we'd need to mention it anywhere else.

Thanks for pointing it out to us.

**Comment by markboos** [comment]
Thanks. I got the php requirement from the requirements for composer. So thats not needed to add in your requirements.
