### ISSUE TITLE
SiteCreate command fails on 3.7 

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-console#58]
Due to whitespace changes in configuration.php-dist in Joomla 3.7 our regexp for configuration.php is not working correctly.

See: https://github.com/joomla/joomla-cms/blob/staging/installation/configuration.php-dist#L65

**Comment by ercanozkaya** [comment]
@stevenrombauts can you see if this looks good? Without this fix running `joomla site:create foo --release staging` will lead to redeclaration of variables in configuration.php

**Comment by stevenrombauts** [comment]
@ercanozkaya Looks good and working as expected.
