### ISSUE TITLE
Failed to start session when using Joomlatools on the CLI with Joomla! 3.7.5

### ISSUE THREAD

**Issue by bweston92** [joomlatools/joomlatools-console#63]
No idea why it wants to start a session but something seems to break.

PHP 7.1
Joomla CMS 3.7.5
Joomla Console tools 1.4.10

```
$ joomla extension:install --www=/var/www mysite 'mod_upload'

                               
  [RuntimeException]           
  Failed to start the session  
                               

extension:install [--www WWW] [--] <site> <extension> (<extension>)...
```

**Comment by stevenrombauts** [comment]
Hi @bweston92! I tried to run through these steps but I can't replicate the issue. Could it be that your mod_upload package is running some custom code on installation? 

To get more output from the console tool you can add the `-vvv` flags: `joomla extension:install --www=/var/www mysite 'mod_upload' -vvv`. Maybe that can shed some light on the issue?

**Comment by bweston92** [comment]
Turned out that the session wasn't compatible with PHP 7.1

**Comment by stevenrombauts** [comment]
@bweston92 Ok, glad to hear the issue is solved on your end as well!
