### ISSUE TITLE
Add Joomla 3.8 compatibility

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-console#65]
Add Joomla 3.8 compatibility.

Verify the following commands:

* [x] site:create
* [x] site:list
* [x] extension:*

**Comment by goldrush-bob** [comment]
I would have expected this commit to now show my 3.8+ sites in the dashboard, which is not the case with my installation. I have just updated to 1.5.x and still do not have 3.8+ visibility. Am I missing something?

**Comment by stevenrombauts** [comment]
@goldrush-bob The fix for 3.8 was added only in v1.4.11. The Joomlatools 1.5 box has this version installed by default so it should work right away. 

Could you make sure you have the 1.5 box installed? You can verify using the command `echo $JOOMLATOOLS_BOX`. Could you also verify the console version with `joomla -V`?

The dashboard should looke like this: [screenshot](https://user-images.githubusercontent.com/77368/32726078-87946df0-c86f-11e7-9756-9cdf58051736.jpg).

**Comment by goldrush-bob** [comment]
Thanks for the follow-up.

Pretty sure I ran the box update to 1.5, but your command reports I’m only running 1.4.4
With console of 1.4.11

Can you let me know what I might have done incorrectly? How do I upgrade to 1.5 box?





--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by stevenrombauts** [comment]
It sounds like the *base* box wasn't updated and you only reinstalled your
working copy. Instructions for upgrading are here:
https://www.joomlatools.com/developer/tools/vagrant/faq/#how-can-i-update-the-box-to-the-latest-version


Hope that helps,
Steven

**Comment by stevenrombauts** [comment]
And one final note, make sure to run the latest versions of Vagrant and
Virtualbox!

**Comment by goldrush-bob** [comment]
Maybe a novice question, but I don’t want to loose anything or have to set up my environment yet again.

Does 'vagrant destroy' kill all the sites I have up and running?
I would really hate to have to set them up all over again. (even from the back-ups from the plugin)

This list doesn’t include the 3.8 + site I have either.

BTW, thanks for this tool! It has become indispensable to my development process!

--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by stevenrombauts** [comment]
@goldrush-bob The backup script mentioned in the FAQ will only backup your databases and the Apache vhost configurations. (You can double check by extracting the `joomla.box.tar` file after backing up and before destroying the box).

Your actual PHP, JS, CSS files and other assets are stored on your host machine so they stay put (inside the `www` directory). Anything else that you might have changed or added *inside* the box will be lost.

Happy to hear you're making good use of the box!

**Comment by goldrush-bob** [comment]
Thanks for the update.
I actually READ the documentation and got it sorted out.

Thanks!

--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by johanjanssens** [comment]
Great to hear! If there is anything else please let us know on chat or forums. Happy Joomla coding!

**Comment by goldrush-bob** [comment]
The restore process was awesome!
I’ve had issues with my box in the past and started over from scratch :P

This made it very painless. I’m back up and running!

I do see a slight issue tho…
The dashboard is cutting off the window displaying my sites. I have more sites than what shows.

I’m sure its just a matter of ‘frame scrolling'



--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by goldrush-bob** [comment]
I managed to fix the scrolling issue for my installation.

I removed the ‘overflow: hidden;’ from line 4499 of assets/css/dashboard.css

Have to say, I’m not a fan of the terminal tool showing by default.
Since I made the above change, the terminal tool is gone. Yea for me!

--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by goldrush-bob** [comment]
I really hate to be a pest, but where do I request a feature?
The documentation says to set up a host record so we can user mysite.dev, however the dashboard doesn’t give this as an option.

Just a thought.

Thanks again!!

--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by stevenrombauts** [comment]
@goldrush-bob Glad to hear you got your issues sorted. For questions such as these, please join us on the [joomlatools/dev chat](http://gitter.im/joomlatools/dev) as this issue is not the place for such discussions. 

About setting up a host record: this has to happen on your host machine, not on the box, so it's impossible for us to do this from the dashboard (which runs *inside* the box).

**Comment by goldrush-bob** [comment]
Yeah, understood.
But to clarify, my question was not about setting up a host record, but rather the ability to modify the link on the dashboard to use the mysite.dev url instead of joomla.box/mysite/

For now, I just edit the scripts manually, but just had to reset them due to the restore.

No worries, thanks for all the help.

--
Thank you,

Bob Brock
Web / IT
Goldrush Getaways
916.722.1648 Ext 5236
http://www.goldrushgetaways.com

**Comment by johanjanssens** [comment]
Thanks great to hear. Can we move this discussion to our forum or chat please? If you can upload a little screenshot of your screen we get a better idea of your problem. 

If you know how to fix the issue you can submit a pull request instead. You can find our contributor guidelines here: https://www.joomlatools.com/developer/contribute/
