### ISSUE TITLE
Issue installing symlinked extension

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-console#71]
https://github.com/joomlatools/textman/pull/431#issuecomment-339886990

It seems Joomla Console has an issue installing a symlinked extension when it has similarly named plugin folder, it somehow calls the `uninstall.sql` when trying install the TEXTman Notify plugin `plugins/textman/notify`.

```
$ joomla site:create textman --symlink=textman -vvv
...
Installing textman ..
Enabling plugin `textman` (ID #10001) ..
Installing textman ..
Enabling plugin `textman` (ID #10002) ..
Installing textman ..
Enabling plugin `textman` (ID #10004) ..
Installing com_textman ..
Installing notify ..
Enabling plugin `notify` (ID #10005) ..
Your new Joomla site has been configured.
You can login using the following username and password combination: admin/admin.
```
It installs everything but it drops the `#__textman_revisions` table and deletes `textman-files` and `textman-images` in the `#__files_containers` table, pretty much everything in the `uninstall.sql`. It works, however, when I renamed the plugin `plg:textman.notify` to `plg:koowa.textman` i.e. moving the notify plugin from `plugins/textman` folder to `plugins/koowa/textman`

**Comment by stevenrombauts** [comment]
@jebbdomingo @ercanozkaya Do we have any idea how this can be solved in the TEXTman repo? Or will it require some exceptions on console level?

**Comment by ercanozkaya** [comment]
I tried to debug this a bit but couldn't get anywhere. Notify is installed last, after textman itself which I think creates the issue but I have no clue how.

**Comment by johanjanssens** [comment]
@ercanozkaya Are you able to replicate the issue? If so, can you add steps to description of ticket so we can have a closer look?

**Comment by ercanozkaya** [comment]
@johanjanssens Yeah I can replicate. In console, when an extension is symlinked on `site:create` command, it discover-installs all extensions that it can. This means Textman dependencies like plugins etc are installed independently. Normally Textman should install these extensions itself. 

The fix here would be to only discover-install symlinked extensions and nothing else.

**Comment by ercanozkaya** [comment]
Closing this one as it doesn't seem to be an issue any longer.
