### ISSUE TITLE
Unlucky option name --mysql_db_prefix

### ISSUE THREAD

**Issue by gorgonz** [joomlatools/joomlatools-console#84]
seen with official version 1.4.11.
All option names use "-" as delimiter, just mysql_db_prefix uses "_". I would suggest to do it in a unique way.
Since there might be a lot of scripts in use, maybe it is a better approach to add the option mysql-db-prefix instead of replacing the old value with it. One could declare the old one as obsolete and remove it at a later time

**Comment by stevenrombauts** [comment]
@gorgonz Thanks, that makes sense. It would be better to rename it to `--mysql-db-prefix`. Feel free to send in a PR for this.
