### ISSUE TITLE
option --mysql_db_prefix will not overwrite the default value j_

### ISSUE THREAD

**Issue by gorgonz** [joomlatools/joomlatools-console#85]
using official version 1.4.11
Using the option --mysql-db-prefix produces an error, That's fine for the moment, because the syntax is not allowed (yet). Using --mysql_db_prefix instead is accepted, but the new value is not used with the table names. They still are prefixed with the default "j_".

**Comment by gorgonz** [comment]
Additional infos:
- I'm running OpenSUSE leap 42.2 
- Here is an example command, that i used:
> joomla site:create jtest  --mysql-login=test:test  --mysql_db_prefix=jt_ --www=/srv/www/htdocs

As can be seen, there is no option --mysql-database, that could prevent the use of option mysql_db_prefix.

**Comment by stevenrombauts** [comment]
Thanks for looking into this @gorgonz. The `--mysql_db_prefix` argument actually has nothing to do with the Joomla **table** prefix, but the *name of the database* that gets created. 

By default, the Console creates a new database for your site `mysite` with the name `sites_mysite`. The `sites_` prefix can be changed using `mysql_db_prefix. 

If you have a requirement to use a different Joomla table prefix, it's easy to make this happen:

1. Add a new argument called `joomla-table-prefix` to the [AbstractDatabase](https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Command/Database/AbstractDatabase.php#L61-L67) class.
1. Replace instances of `j_` with the value from this new argument. Most notable in the [database:install](https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Command/Database/Install.php#L101) command.

PRs always welcome :)

**Comment by thuebschmann** [comment]
I think the prefix paramter should allways use if is set.
some provider does#t allows create database at console
