### ISSUE TITLE
Upgrade symfony/console

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-console#86]
The symfony/console package version is currently locked at 2.7.x, while 4.0 is already released. Update composer.json and the code accordingly.

**Comment by glumanda99** [comment]
Yes, please update, can not install this one without removing symfony console first. Don't know if I could have both installed at the same time globally.

**Comment by johanjanssens** [comment]
@stevenrombauts Is this something we can resolve with priority in a maintenance release?

**Comment by stevenrombauts** [comment]
@glumanda99 You can use this branch now to install alongside packages that require the newer symfony/console: `composer global require joomlatools/console:dev-feature/86-symfony`, until we release this.

**Comment by johanjanssens** [comment]
If are not using phing lets remove it. Could warrant a maintenance release of the box too, or can the uninstall be handled during composer update?

**Comment by stevenrombauts** [comment]
@johanjanssens Rolling out a little maintenance release for the box will be the best way forward.  Adding a hook and logic to remove it is probably going to be complicated and result in one big hack.

I'll prepare a maintenance release, should also fix joomlatools/joomlatools-vagrant#123 and joomlatools/joomlatools-vagrant#121 along with this Console issue.

**Comment by stevenrombauts** [comment]
Note: we still require this for building packages, so we need to upgrade it on the box. Ticket has been amended.

**Comment by johanjanssens** [comment]
@stevenrombauts agreed.

**Comment by stevenrombauts** [comment]
@glumanda99 This change has been included in the v1.5.1 release.
