### ISSUE TITLE
site:init

### ISSUE THREAD

**Issue by PierreCorell** [joomlatools/joomlatools-console#89]
Hello joomlatools,

really nice CLI tool, great and very helpful.

In my eyes a very important function is missed to use it on a daily base - a command to initialize an existing site like for eg. composer does.
I did not check your routines so much for now, but maybe you do see an option to add a class / cmd for this feature request?

**Comment by stevenrombauts** [comment]
@PierreCorell Hi Pierre, nice to meet you!

I'm not sure I understand what you mean by "initializing"? If you mean to set up the database and configuration if you already have the codebase in place, you can run [joomla site:install mysite](https://www.joomlatools.com/developer/tools/console/commands/site/#siteinstall).

By the way, we only use issues for bug reports or for planned features. If you would like to discuss ideas or have any other question, feel free to join us on our [Gitter chat](http://gitter.im/joomlatools/dev) or send a message to our [mailing list](https://groups.google.com/forum/#!forum/joomlatools-dev). Thanks!

**Comment by PierreCorell** [comment]
Hi Steven, thank you for your reply.
Hopefully I can comment my feature request ;)

I meant that the tools is not very useful if I am not able to integrate it into any existing (already built) site to manage them more comfortably. I have dozens of them... 

joomla site:install mysite is just for creating a new database if I correctly got it - but what if I do have an already rich populated one?

**Comment by stevenrombauts** [comment]
@PierreCorell If you already have the database and codebase in place, and you only need configuration.php to be created, you can use [joomla site:config mysite](https://www.joomlatools.com/developer/tools/console/commands/site/#siteconfigure). 

If you need to create the virtualhost configuration in Apache, you can use [joomla vhost:create mysite](https://www.joomlatools.com/developer/tools/console/commands/vhost/#vhostcreate), although this command will probably only work 100% correctly on our Vagrant box.

For any other questions or discussions, see you on Gitter!
