### ISSUE TITLE
Don't work "joomla site:create  test"

### ISSUE THREAD

**Issue by progreccor** [joomlatools/joomlatools-console#91]
![2018-04-07_12-34-40](https://user-images.githubusercontent.com/3103677/38453554-16dc3f62-3a60-11e8-8fce-18bca75faf97.png)
### Describe your environment

  * OS: CentOS 7
  * Joomla version: 3.8.6
  * Joomlatools Console version: 1.5.0
  * Are you working on the Joomlatools Vagrant box: no

### Describe the problem:
try to use your command
joomla site:create  test

and get 

#### Observed Results:

``` Downloading https://github.com/joomla/joomla-cms - this could take a few minutes ..

gzip: /root/.config/composer/vendor/joomlatools/console/bin/.files/cache/7522513af9d772a10efbc54fc410dbce/current.tar.gz: not in gzip format


  [RuntimeException]
  Downloaded tar archive "current.tar.gz" could not be verified. A common cause is an interrupted download:
   check your internet connection and try again.

**Comment by progreccor** [comment]
here is what I get
![default](https://user-images.githubusercontent.com/3103677/38506242-f42ed7ea-3c21-11e8-8599-6e23712543f4.png)

**Comment by stevenrombauts** [comment]
@progreccor Can you take a look at the `current.tar.gz` file? If it was a failed download, the file might contain a clue to what went wrong.

You can check its contents with `nano /root/.config/composer/vendor/joomlatools/console/bin/.files/cache/7522513af9d772a10efbc54fc410dbce/current.tar.gz`.

If for some reason downloading does not work, you can try cloning the repository: `joomla site:create test --clone`.

**Comment by progreccor** [comment]
the folder is empty

**Comment by progreccor** [comment]
`[root@localhost cache]# joomla site:create  test --clone


  [RuntimeException]
  The --clone flag requires a valid Git repository
`

**Comment by stevenrombauts** [comment]
@progreccor Is `git` installed on your system? What's the output of this command: `GIT_SSH_COMMAND=\"ssh -oBatchMode=yes\" GIT_ASKPASS=/bin/echo git ls-remote https://github.com/joomla/joomla-cms`? 

That's the one we use to check if the repository a valid one.
