### ISSUE TITLE
Joomla 4 compatibility

### ISSUE THREAD

**Issue by frogydiak** [joomlatools/joomlatools-console#94]
### Are you in the right place?
I think this is a bug.

### Describe your environment

  * OS: Sierra
  * Joomla version: 4.0-dev
  * Joomlatools Console version: Joomla Console tools 1.5.2
  * Are you working on the Joomlatools Vagrant box: no (using valet)

### Describe the problem:
I am trying to register my custom component and I am getting a PhP Fatal Error. 

#### Steps to reproduce:
I am doing:

`joomla extension:register --www=/Volumes/DataDrive/Sites/Joomla joomla4 com_church`

#### Observed Results:

`joomla extension:register --www=/Volumes/DataDrive/Sites/Joomla joomla4 com_church
PHP Fatal error:  Class Joomlatools\Console\Joomla\Application contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\Application\AbstractApplication::doExecute) in /Volumes/UserDrive/Users/username/.composer/vendor/joomlatools/console/src/Joomlatools/Console/Joomla/Application.php on line 24

Fatal error: Class Joomlatools\Console\Joomla\Application contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\Application\AbstractApplication::doExecute) in /Volumes/UserDrive/Users/username/.composer/vendor/joomlatools/console/src/Joomlatools/Console/Joomla/Application.php on line 24`

**Comment by laoneo** [comment]
Looking forward to J4 compatibility as development reached beta status. Means no breaking changes anymore.

**Comment by johanjanssens** [comment]
@laoneo Thanks. We are planning to work on this, it's a bit of juggling of resources and priorities at the moment. Changes in Joomla 4 are very considerable and will require a bit of time before we have it all right. Help is always welcome.

**Comment by laoneo** [comment]
If you have questions, don't hesitate to ask.

**Comment by johanjanssens** [comment]
Will do.
