### ISSUE TITLE
Need help to work in production mode present bug errror in cli console

### ISSUE THREAD

**Issue by juanma386** [joomlatools/joomlatools-console#96]
### Describe your environment

  * OS: Debian 9 Webmin and Virtualmin Production
  * Joomla version: last version
  * Joomlatools Console version: cli $ joomla
  * Are you working on the Joomlatools Vagrant box: yes/no

### Describe the problem:

$ joomla site:create /home/stockuno/domains/omega.stockuno.cf/public_html/joomla-test
mkdir: no se puede crear el directorio «/var/www//home»: Permiso denegado
sh: 1: cd: can't cd to /var/www//home/stockuno/domains/omega.stockuno.cf/public_html/joomla-test
SSL was not enabled for the site. One or more certificate files are missing.

#### Steps to reproduce:

  1. instaled in the production mode
  2. user autenticate peding is /bin/false and production mode

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by johanjanssens** [comment]
Hello Juan, for support questions please use our community resources:

- Mailing list: https://groups.google.com/forum/#!forum/joomlatools-dev
- Chat: http://gitter.im/joomlatools/dev

Thanks!
