### ISSUE TITLE
Errors when installing extensions using extension:install

### ISSUE THREAD

**Issue by mwaeckerlin** [joomlatools/joomlatools-console#97]
### Describe your environment

  * OS: alpine linux in docker
  * Joomla version: latest (3.8.13) just downloaded with joomla console
  * Joomlatools Console version: Joomla Console tools 1.5.2
  * Are you working on the Joomlatools Vagrant box: no

### Describe the problem:

I try to setup Joomla in a docker imaged, based on alpine linux, derieved from [mwaeckerlin/php-fpm](https://github.com/mwaeckerlin/php-fpm). Basic Joomla now works, but when I try to install any extension, I get several error messages.

#### Steps to reproduce:

Create file `Dockerfile`: 
```
FROM mwaeckerlin/php-fpm

ENV LANGUAGES      ""
ENV MYSQL_USER     "root"
ENV MYSQL_PASSWORD "ert456"
ENV MYSQL_DATABASE "websites"
ENV MYSQL_HOST     "mysql"
ENV WEB_ROOT_PATH  "/joomla/websites"

ENV CONTAINER      "websites"
USER root
RUN apk add composer git mysql-client php7-mbstring php7-simplexml php7-session php7-mysqli php7-mbstring php7-bz2 php7-zip \
 && (test ! -d "${WEB_ROOT_PATH%/*}" || rm -rf "${WEB_ROOT_PATH%/*}") \
 && mkdir -p "${WEB_ROOT_PATH%/*}" \
 && mkdir /composer \
 && cd /composer \
 && composer require joomlatools/console \
 && /composer/vendor/bin/joomla site:download --www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" \
 && chown -R nginx "${WEB_ROOT_PATH%/*}" \
 && sed -i 's,^ *;\? *session.save_path =.*,session.save_path = "/tmp",' /etc/php7/php.ini \
 && mkdir /joomla/plugins \
 && mv /start.sh /start-php-fpm.sh
USER nginx
ADD start.sh /start.sh
```

Create file `start.sh` and set it's executable mode `chmod +x start.sh`: 
```bash
#!/bin/sh -e

echo | mysql -u root -pert456 -h mysql websites || \
    /composer/vendor/bin/joomla database:install \
                                --www "${WEB_ROOT_PATH%/*}" \
                                -L "${MYSQL_USER}:${MYSQL_PASSWORD}" \
                                --mysql-database "${MYSQL_DATABASE}" \
                                -H "${MYSQL_HOST}" \
                                "${WEB_ROOT_PATH##*/}"

test -e ${WEB_ROOT_PATH}/configuration.php || \
    /composer/vendor/bin/joomla site:configure \
                                --www "${WEB_ROOT_PATH%/*}" \
                                -L "${MYSQL_USER}:${MYSQL_PASSWORD}" \
                                --mysql-database "${MYSQL_DATABASE}" \
                                -H "${MYSQL_HOST}" \
                                "${WEB_ROOT_PATH##*/}"
sed -i "s,public *\$session_handler *=.*;,public \$session_handler = 'none';," ${WEB_ROOT_PATH}/configuration.php

/start-php-fpm.sh
```

1.  build docker image: `docker build --rm --force-rm -t mwaeckerlin/joomla .`
1. run mysql database: `docker run --name joomla-mysql -d -e MYSQL_ROOT_PASSWORD=ert456 mysql:5`
1. run the joomla image: `docker run -d --name joomla -p 8001:8080 --link joomla-mysql:mysql mwaeckerlin/joomla`
1. open a shell in the joomla container: `docker exec -it joomla sh`
1. try to install an extension, e.g. VirtueMart: `/composer/vendor/bin/joomla extension:install 
--www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" com_virtuemart`

#### Observed Results:

Get error messages:
```
nginx@php-fpm[59717c39181a]:/$ /composer/vendor/bin/joomla extension:install --www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" com_virtuemart
PHP Notice:  Constant JROUTER_MODE_RAW already defined in /joomla/websites/libraries/import.php on line 60
Notice: Constant JROUTER_MODE_RAW already defined in /joomla/websites/libraries/import.php on line 60
PHP Notice:  Constant JROUTER_MODE_SEF already defined in /joomla/websites/libraries/import.php on line 67
Notice: Constant JROUTER_MODE_SEF already defined in /joomla/websites/libraries/import.php on line 67
```

Does not install the component, `com_virtuemart` is missing:
```
nginx@php-fpm[59717c39181a]:/$ ls /joomla/websites/components/
com_ajax            com_fields          com_newsfeeds
com_banners         com_finder          com_search
com_config          com_mailto          com_tags
com_contact         com_media           com_users
com_content         com_menus           com_wrapper
com_contenthistory  com_modules         index.html
```

#### Expected Results:

Installation succeeds.

#### More Information

I also tried to install from zip-files using `extension:installfile`, but I get the same result.

**Comment by stevenrombauts** [comment]
@mwaeckerlin I don't see any error message in your output, only a few notices. I'm not sure where these are coming from but I only get these when trying to install Virtuemart, so I'm sure it's related to their installer.

I tried installing Virtuemart on our [Joomlatools Vagrant](https://www.joomlatools.com/developer/tools/vagrant/) box and that succeeded without issues:

```
joomla site:create test
wget https://dev.virtuemart.net/attachments/download/1144/com_virtuemart.3.4.2.9966_package_or_extract.zip -O /tmp/pkg_virtuemart.3.4.2.zip
joomla extension:installfile test /tmp/pkg_virtuemart.3.4.2.zip 
ls -lah /var/www/test/components/ | grep com_virtuemart # lists two com_virtuemarts directories
```

I tried the same approach using `extension:installfile` on your docker container, and Virtuemart is installed fine here. The installer does throw some warnings but installation seems to have succeeded:

```
nginx@php-fpm[d92a0feb90e2]:/$ /composer/vendor/bin/joomla extension:installfile --www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" /tmp/pkg_virtuemart.3.4.2.zip
PHP Notice:  Constant JROUTER_MODE_RAW already defined in /joomla/websites/libraries/import.php on line 60
Notice: Constant JROUTER_MODE_RAW already defined in /joomla/websites/libraries/import.php on line 60
PHP Notice:  Constant JROUTER_MODE_SEF already defined in /joomla/websites/libraries/import.php on line 67
Notice: Constant JROUTER_MODE_SEF already defined in /joomla/websites/libraries/import.php on line 67
PHP Warning:  array_merge(): Argument #2 is not an array in /joomla/websites/administrator/components/com_virtuemart/models/config.php on line 548
PHP Warning:  array_unique() expects parameter 1 to be array, null given in /joomla/websites/administrator/components/com_virtuemart/models/config.php on line 549
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /joomla/websites/plugins/vmpayment/klarna/klarna/api/transport/xmlrpc-3.0.0.beta/lib/xmlrpc.inc on line 44
nginx@php-fpm[d92a0feb90e2]:/$ ls -lah /joomla/websites/components/ | grep com_virtuemart
drwxr-xr-x    8 nginx    nginx       4.0K Oct 28 15:34 com_virtuemart
drwxr-xr-x    2 nginx    nginx       4.0K Oct 28 15:34 com_virtuemart_allinone
```

Another little note, for `extension:install` to work, you need to [symlink the extension](https://www.joomlatools.com/developer/tools/console/getting-started/#symlink-your-code-into-a-joomla-installation) into your installation first. Your example commands don't seem to mention this?

I am unable to replicate this so closing this ticket.

**Comment by mwaeckerlin** [comment]
Ok, at first sight, it seems that my fault was to extract virtuemart package and to install the components separately. When I install from the GUI, that's necessary, but here obviously not.

I'll test again with all other packages.

**Comment by mwaeckerlin** [comment]
@stevenrombauts, now it works for virtuemart, but only for virtuemart, the installation of any other plugin fails.

E.g. a simple one: [kickgdpr](https://extensions.joomla.org/extension/kick-gdpr-dsgvo/):
```bash
nginx@php-fpm[692192ace4d8]:/$ wget -O/tmp/kickgdpr-2.4.0.zip https://github.
com/nielsnuebel/kickgdpr/archive/2.4.0.zip
Connecting to github.com (192.30.253.112:443)
Connecting to codeload.github.com (192.30.253.121:443)
kickgdpr-2.4.0.zip   100% |****************************| 37900   0:00:00 ETA
nginx@php-fpm[692192ace4d8]:/$ /composer/vendor/bin/joomla extension:installf
ile --www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" /tmp/kickgdpr-2.4.0.zi
p 
PHP Notice:  Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
Notice: Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
PHP Notice:  Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
Notice: Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
nginx@php-fpm[692192ace4d8]:/$ ls -lah /joomla/websites/components/ | grep ki
ck
nginx@php-fpm[692192ace4d8]:/$ find /joomla/websites -iname '*kick*'
nginx@php-fpm[692192ace4d8]:/$
```

Or download and install [AWO-Coupon](https://www.awocoupon.com/) (free download) → nothing gets installed!

```bash
nginx@php-fpm[692192ace4d8]:/$ /composer/vendor/bin/joomla extension:installf
ile --www "${WEB_ROOT_PATH%/*}" "${WEB_ROOT_PATH##*/}" /tmp/plugins/com_awoco
upon-2.0.26.zip 
PHP Notice:  Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
Notice: Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
PHP Notice:  Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
Notice: Undefined index: REQUEST_URI in /joomla/websites/includes/framework.php on line 34
nginx@php-fpm[692192ace4d8]:/$ find /joomla/websites -iname '*awo*'
nginx@php-fpm[692192ace4d8]:/$
```

Then I also tried some commercial (payed) plugins, but none of them gets installed.

Why?

**Comment by stevenrombauts** [comment]
@mwaeckerlin I've tried KickGDPR again but that works without issue here. Here's my output on the Vagrant box:

```bash
$ joomla site:create joomla39
Your new Joomla site has been configured.
You can login using the following username and password combination: admin/admin.

$ wget --quiet https://github.com/nielsnuebel/kickgdpr/archive/2.4.0.zip -O /tmp/kickgdpr.zip

$ joomla extension:installfile joomla39 /tmp/kickgdpr.zip

$ ls -lah /var/www/joomla39/plugins/system | grep kickgdpr
9:drwxr-xr-x  9 501 dialout 288 Nov 10 14:42 kickgdpr/
```

The console does not really get involved much in the installation itself. We basically pass the path to package source to Joomla's `JInstaller` and let it run from there. ([code](https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Command/Extension/InstallFile.php#L62-L109)). 

Some packages run custom installer scripts, and it's most likely something is going wrong in there. I suggest you try to debug those and see what might be going wrong that's specific to your working environment.

**Comment by mwaeckerlin** [comment]
@stevenrombauts, what I am missing is any kind of trace, log, error message or similar that would help me find the problem. Even the return code is `0`. Is there nothing I could check?

**Comment by stevenrombauts** [comment]
@mwaeckerlin I agree, this is something we're missing. The trouble is that we don't have a good way to actually get good responses from Joomla; we're basically just handling it as a black box. We bootstrap Joomla, give it a package to install and then just let it run.

We do have the verbosity flag `-vvv` which will try to pass some more information about symlinking and installation. Apart from that, we expect Joomla's installer code to output errors and exceptions but this is often not the case. Any suggestions on how to improve on this are most welcome!
