### ISSUE TITLE
Redundant library import rises errors

### ISSUE THREAD

**Issue by miljan-aleksic** [joomlatools/joomlatools-console#99]
### Environment

  * OS: Debian
  * Joomla version: 3.9.0
  * Joomlatools Console version: 1.5.1
  * Are you working on the Joomlatools Vagrant box: no

### Problem:

The `extension:install` and other related commands are failing to execute when Joomla `error_reporting` is set to Development:

```
Notice: Constant JROUTER_MODE_RAW already defined in /var/www/html/libraries/import.php on line 60
Notice: Constant JROUTER_MODE_SEF already defined in /var/www/html/libraries/import.php on line 67
Warning: session_name(): Cannot change session name when headers already sent in /var/www/html/libraries/joomla/session/handler/native.php on line 128
Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /var/www/html/libraries/joomla/session/handler/native.php on line 235
```

The conflict relies on both `libraries/import.php` and `libraries/import.legacy.php` being required. The first directly by [Bootstrapper](https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Joomla/Bootstrapper.php#L95) and the latest indirectly by `includes/framework.php` which will ultimately require it. Usually this kind of conflicts would have been unnoticed because of the use of `required_once` statement, but in this case those are two different files.

This has been already reported at https://github.com/joomlatools/joomlatools-console/issues/97 but aparently not identified as an issue, most likely because of the `error_reporting` setting.

**Comment by stevenrombauts** [comment]
Closed in #100
